{{- if .Values.vault.enabled }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ .Chart.Name }}-vault-secret
  namespace: {{ .Values.global.namespace }}
spec:
  destination:
    create: true
    name: {{ .Chart.Name }}-secrets
  mount: {{ .Values.vault.mount }}
  path: {{ .Values.vault.path }}
  type: kv-v2
  refreshAfter: {{ .Values.vault.refreshAfter }}
{{- end }}
