apiVersion: v2
name: app
description: Generic Application - Unicamp
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: app-backend
    version: "1.0.0"
    repository: "file://./app-backend"
    condition: backend.enabled
  - name: app-frontend
    version: "1.0.0"
    repository: "file://./app-frontend"
    condition: frontend.enabled
  - name: app-database
    version: "1.0.0"
    repository: "file://./app-database"
    condition: database.enabled
