global:
  namespace: app
  registry: registry.nuvem.unicamp.br/project/app
  environment: hom
  domain: app.tkg-hom.nuvem.unicamp.br

vault:
  mount: project-hom

backend:
  enabled: true
frontend:
  enabled: true
database:
  enabled: true

app-backend:
  image:
    tag: "latest"
  replicas: 1
  springProfile: hom
  resources:
    requests:
      memory: "800Mi"
      cpu: "250m"
    limits:
      memory: "1000Mi"
      cpu: "500m"
  vault:
    mount: project-hom
    path: app/backend

app-frontend:
  image:
    tag: "latest"
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "200m"
  ingress:
    tls:
      enabled: false
  vault:
    mount: project-hom
    path: app/frontend

app-database:
  enabled: true
  storage:
    size: "2Gi"
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  vault:
    mount: project-hom
    path: app/database
